// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241124211323_ImageTable")]
    partial class ImageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApplication1.Model.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Url = "https://my-jsonserver.typicode.com/ck-pacificdev/tech-test/images/1"
                        },
                        new
                        {
                            Id = 2,
                            Url = "https://my-jsonserver.typicode.com/ck-pacificdev/tech-test/images/2"
                        },
                        new
                        {
                            Id = 3,
                            Url = "https://my-jsonserver.typicode.com/ck-pacificdev/tech-test/images/3"
                        },
                        new
                        {
                            Id = 4,
                            Url = "https://my-jsonserver.typicode.com/ck-pacificdev/tech-test/images/4"
                        },
                        new
                        {
                            Id = 5,
                            Url = "https://my-jsonserver.typicode.com/ck-pacificdev/tech-test/images/5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
